CREATE PROCEDURE [Lore].[spNPCs_InsertNPC]
	@Name VARCHAR(100),
	@Race VARCHAR(30),
	@Description VARCHAR(MAX),
	@Biography VARCHAR(MAX),
	@Title VARCHAR(100),
	@LevelOrCr VARCHAR(6),
	@Speed INT,
	@HitPoints INT,
	@ArmorClass INT,
	@StatArray VARCHAR(36),
	@ProficiencyBonus INT,
	@SpellSaveDC INT,
	@SpellList VARCHAR(MAX),
	@SaveProficienciesList VARCHAR(MAX),
	@SkillProficienciesList VARCHAR(MAX),
	@ItemProficienciesList VARCHAR(MAX),
	@ActionList VARCHAR(MAX),
	@FeatureList VARCHAR(MAX),
	@EquipmentList VARCHAR(MAX),
	@LocationId INT,
	@BirthDate VARCHAR(MAX),
	@BirthAgeId INT,
	@DeathDate VARCHAR(MAX),
	@DeathAgeId INT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO [Lore].[NPCs]
		([Name],
		[Race],
		[Description],
		[Biography],
		[Title],
		[LevelOrCR],
		[Speed],
		[HitPoints],
		[ArmorClass],
		[StatArray],
		[ProficiencyBonus],
		[SpellSaveDC],
		[SpellList],
		[SaveProficienciesList],
		[SkillProficienciesList],
		[ItemProficienciesList],
		[ActionList],
		[FeatureList],
		[EquipmentList],
		[LocationId],
		[BirthDate],
		[BirthAgeId],
		[DeathDate],
		[DeathAgeId])
	VALUES
		(@Name,
		@Race,
		@Description,
		@Biography,
		@Title,
		@LevelOrCr,
		@Speed,
		@HitPoints,
		@ArmorClass,
		@StatArray,
		@ProficiencyBonus,
		@SpellSaveDC,
		@SpellList,
		@SaveProficienciesList,
		@SkillProficienciesList,
		@ItemProficienciesList,
		@ActionList,
		@FeatureList,
		@EquipmentList,
		@LocationId,
		@BirthDate,
		@BirthAgeId,
		@DeathDate,
		@DeathAgeId);
		
END
